// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wftnxmfqoxjrirpveqxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdG54bWZxb3hqcmlycHZlcXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzAyOTMsImV4cCI6MjA2OTIwNjI5M30.THOKdP7m3NABbd4hAkBvACZIWyRmGmeTo9JPynesJjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});